INSERT IGNORE INTO courses (code, name, department_id, semester, subject_type) VALUES
('DCOS101', 'Communication Skill-I', 4, 1, 'Theory'),
('DCOM102', 'Applied Maths-I', 4, 1, 'Theory'),
('DEE103',  'Electrical and Electronics Engineering', 4, 1, 'Theory'),
('DME104',  'Elements of Mechanical Engineering', 4, 1, 'Theory'),
('DCO105',  'Fundamental of Computers', 4, 1, 'Theory'),
('DEE113',  'Electrical and Electronics Engineering Lab', 4, 1, 'Practical'),
('DME116',  'Workshop Practice', 4, 1, 'Practical'),
('DME117',  'Engineering Drawing', 4, 1, 'Practical'),
('DCO115',  'P.C. Software Lab', 4, 1, 'Practical'),
('DCOM201', 'Applied Maths-II', 4, 2, 'Theory'),
('DCOP202', 'Applied Physics', 4, 2, 'Theory'),
('DEL203',  'Electronics Devices and Application', 4, 2, 'Theory'),
('DCOC204', 'Engineering Chemistry & Environmental Science', 4, 2, 'Theory'),
('DCO205',  'Programming in C', 4, 2, 'Theory'),
('DCOP212', 'Applied Physics Lab', 4, 2, 'Practical'),
('DEL213',  'Electronics Devices and Application Lab', 4, 2, 'Practical'),
('DCOC214', 'Engineering Chemistry Lab', 4, 2, 'Practical'),
('DCO215',  'Programming in C Lab', 4, 2, 'Practical'),
('DCO301',  'Computer Oriented Numerical Methods', 4, 3, 'Theory'),
('DCO302',  'Object Oriented Programming', 4, 3, 'Theory'),
('DEE303',  'Signals & Systems', 4, 3, 'Theory'),
('DCO304',  'Computer Architecture', 4, 3, 'Theory'),
('DEL306',  'Digital Electronics', 4, 3, 'Theory'),
('DCO312',  'Object Oriented Programming Lab', 4, 3, 'Practical'),
('DCO314',  'Computer Workshop', 4, 3, 'Practical'),
('DCO315',  'Computer System & Maintenance', 4, 3, 'Practical'),
('DEL316',  'Digital Electronics Lab', 4, 3, 'Practical'),
('DCOS401', 'Communication Skills-II', 4, 4, 'Theory'),
('DCO402',  'Database Management System', 4, 4, 'Theory'),
('DCO403',  'Operating System', 4, 4, 'Theory'),
('DCO404',  'Data Structures', 4, 4, 'Theory'),
('DEL405',  'Microprocessor & Microcontroller', 4, 4, 'Theory'),
('DCO412',  'Database Management System Lab', 4, 4, 'Practical'),
('DCO413',  'Operating System Lab', 4, 4, 'Practical'),
('DCO414',  'Data Structures Lab', 4, 4, 'Practical'),
('DEL415',  'Microprocessor Programming Lab', 4, 4, 'Practical'),
('DCO501',  'Computer Graphics', 4, 5, 'Theory'),
('DCO502',  'Web Technology', 4, 5, 'Theory'),
('DCO503',  'Data Communication & Computer Networks', 4, 5, 'Theory'),
('DCO504',  'Software Engineering', 4, 5, 'Theory'),
('DCO505',  'Java Programming', 4, 5, 'Theory'),
('DCO511',  'Computer Graphics & Multimedia Lab', 4, 5, 'Practical'),
('DCO512',  'Web Technology Lab', 4, 5, 'Practical'),
('DCO513',  'Computer Networks Lab', 4, 5, 'Practical'),
('DCO515',  'Java Programming Lab', 4, 5, 'Practical'),
('DCO520',  'Minor Project', 4, 5, 'Practical'),
('DCO601',  'Advanced RDBMS', 4, 6, 'Theory'),
('DCO602',  'Visual Programming', 4, 6, 'Theory'),
('DCO603',  'Information Security & Cyber Law', 4, 6, 'Theory'),
('DCO605',  'Artificial Intelligence', 4, 6, 'Theory'),
('DCO608',  'ICT Management & Entrepreneurship Development', 4, 6, 'Theory'),
('DCO611',  'RDBMS Lab', 4, 6, 'Practical'),
('DCO612',  'Visual Programming Lab', 4, 6, 'Practical'),
('DCO620',  'Project', 4, 6, 'Practical'),
('DCO630',  'Industrial Training & Visits', 4, 6, 'Practical');
