INSERT IGNORE INTO courses (code, name, department_id, semester, subject_type) VALUES
('DCES-101', 'Communication Skills-I', 1, 1, 'Theory'),
('DCEP-102', 'Applied Physics', 1, 1, 'Theory'),
('DCEC-103', 'Applied Chemistry', 1, 1, 'Theory'),
('DCEM-104', 'Applied Mathematics-I', 1, 1, 'Theory'),
('DCE-105',  'Applied Mechanics', 1, 1, 'Theory'),
('DCEP-112', 'Applied Physics Lab', 1, 1, 'Practical'),
('DCEC-113', 'Applied Chemistry Lab', 1, 1, 'Practical'),
('DCE-115',  'Applied Mechanics Lab', 1, 1, 'Practical'),
('DME-116',  'Workshop Practice', 1, 1, 'Practical'),
('DCEM-201', 'Applied Mathematics-II', 1, 2, 'Theory'),
('DEE-202',  'Basic Electrical Engineering', 1, 2, 'Theory'),
('DME-203',  'Elements of Mechanical Engineering', 1, 2, 'Theory'),
('DCE-205',  'Surveying-I', 1, 2, 'Theory'),
('DME-206',  'Engineering Drawing-I', 1, 2, 'Theory'),
('DEE-212',  'Basic Electrical Engineering Lab', 1, 2, 'Practical'),
('DME-213',  'Elements of Mechanical Engineering Lab', 1, 2, 'Practical'),
('DCE-215',  'Surveying-I Lab', 1, 2, 'Practical'),
('DME-216',  'Engineering Drawing-I Lab', 1, 2, 'Practical'),
('DCE-301',  'Building Construction', 1, 3, 'Theory'),
('DCE-302',  'Irrigation Engineering', 1, 3, 'Theory'),
('DCE-303',  'Surveying-II', 1, 3, 'Theory'),
('DCE-304',  'Hydraulics', 1, 3, 'Theory'),
('DCA-305',  'Computer Application', 1, 3, 'Theory'),
('DCE-311',  'Building Construction Lab', 1, 3, 'Practical'),
('DCE-313',  'Surveying-II Lab', 1, 3, 'Practical'),
('DCE-314',  'Hydraulics Lab', 1, 3, 'Practical'),
('DCA-315',  'Computer Application Lab', 1, 3, 'Practical'),
('DCES-401', 'Communication Skills-II', 1, 4, 'Theory'),
('DCE-402',  'Concrete Technology', 1, 4, 'Theory'),
('DCE-403',  'Theory of Structures', 1, 4, 'Theory'),
('DCE-404',  'Environmental Engineering-I', 1, 4, 'Theory'),
('DCE-405',  'Construction Materials', 1, 4, 'Theory'),
('DCE-412',  'Concrete Technology Lab', 1, 4, 'Practical'),
('DCE-413',  'Theory of Structures Lab', 1, 4, 'Practical'),
('DCE-414',  'Environmental Engineering-I Lab', 1, 4, 'Practical'),
('DCE-416',  'Civil Engineering Drawing-I', 1, 4, 'Practical'),
('DCE-501',  'Soil Mechanics & Foundation Engineering', 1, 5, 'Theory'),
('DCE-502',  'Design of R.C.C. Structures-I', 1, 5, 'Theory'),
('DCE-503',  'Analysis of Structures', 1, 5, 'Theory'),
('DCE-504',  'Surveying-III', 1, 5, 'Theory'),
('DCE-505',  'Construction Management & Accounts', 1, 5, 'Theory'),
('DCE-511',  'Soil Mechanics & Foundation Engineering Lab', 1, 5, 'Practical'),
('DCE-514',  'Surveying-III Lab', 1, 5, 'Practical'),
('DCE-515',  'CAD in Civil Engineering Practice', 1, 5, 'Practical'),
('DCE-516',  'Civil Engineering Drawing-II', 1, 5, 'Practical'),
('DCE-520',  'Survey Camp', 1, 5, 'Practical'),
('DCE-601',  'Transportation Engineering', 1, 6, 'Theory'),
('DCE-602',  'Design of Steel Structures', 1, 6, 'Theory'),
('DCE-603',  'Estimating & Costing', 1, 6, 'Theory'),
('DCE-604',  'Design of R.C.C. Structures-II', 1, 6, 'Theory'),
('DCE-605',  'Environmental Engineering-II', 1, 6, 'Theory'),
('DCE-611',  'Transportation Engineering Lab', 1, 6, 'Practical'),
('DCE-615',  'Environmental Engineering-II Lab', 1, 6, 'Practical'),
('DCE-620',  'Project', 1, 6, 'Practical'),
('DCE-630',  'Industrial Training & Visits', 1, 6, 'Practical');
