INSERT IGNORE INTO courses (code, name, department_id, semester, subject_type) VALUES
('DELS-101',  'Communication Skills-I', 5, 1, 'Theory'),
('DELP-102',  'Applied Physics', 5, 1, 'Theory'),
('DELC-103',  'Applied Chemistry', 5, 1, 'Theory'),
('DELM-104',  'Applied Maths-I', 5, 1, 'Theory'),
('DEE-105',   'Electrical Engineering-I', 5, 1, 'Theory'),
('DELP-112',  'Applied Physics Lab', 5, 1, 'Practical'),
('DELC-113',  'Applied Chemistry Lab', 5, 1, 'Practical'),
('DEE-115',   'Electrical Engineering-I Lab', 5, 1, 'Practical'),
('DME-EL116', 'Workshop Practice', 5, 1, 'Practical'),
('DELM-201',  'Applied Maths-II', 5, 2, 'Theory'),
('DEL-202',   'Digital Electronics', 5, 2, 'Theory'),
('DME-EL203', 'Elements of Mechanical Engineering', 5, 2, 'Theory'),
('DEE-205',   'Electrical Engineering-II', 5, 2, 'Theory'),
('DEL-205',   'Networks & Transmission Lines', 5, 2, 'Theory'),
('DEL-212',   'Digital Electronics Lab', 5, 2, 'Practical'),
('DME-EL213', 'Elements of Mechanical Engineering Lab', 5, 2, 'Practical'),
('DEL-215',   'Networks & Transmission Lines Lab', 5, 2, 'Practical'),
('DME-EL216', 'Engineering Drawing', 5, 2, 'Practical'),
('DEL-301',   'Electronic Devices & Circuits-I', 5, 3, 'Theory'),
('DEL-302',   'Data Communication & Networking', 5, 3, 'Theory'),
('DEL-303',   'Digital System Design', 5, 3, 'Theory'),
('DEL-304',   'Principles of Communication', 5, 3, 'Theory'),
('DEE-305',   'Measurements & Measuring Instruments', 5, 3, 'Theory'),
('DEL-311',   'Electronic Devices & Circuits-I Lab', 5, 3, 'Practical'),
('DEL-312',   'Data Communication & Networking Lab', 5, 3, 'Practical'),
('DEL-313',   'Digital System Design Lab', 5, 3, 'Practical'),
('DEE-315',   'Measurements & Measuring Instruments Lab', 5, 3, 'Practical'),
('DELS-401',  'Communication Skills-II', 5, 4, 'Theory'),
('DEL-402',   'Industrial Electronics', 5, 4, 'Theory'),
('DEL-403',   'Microprocessors & Applications', 5, 4, 'Theory'),
('DEL-404',   'Electronic Devices & Circuits-II', 5, 4, 'Theory'),
('DCA-405',   'Computer Applications', 5, 4, 'Theory'),
('DEL-412',   'Industrial Electronics Lab', 5, 4, 'Practical'),
('DEL-413',   'Microprocessors & Applications Lab', 5, 4, 'Practical'),
('DEL-414',   'Electronic Devices & Circuits-II Lab', 5, 4, 'Practical'),
('DCA-415',   'Computer Applications Lab', 5, 4, 'Practical'),
('DEL-501',   'Electronic Devices & Circuits-III', 5, 5, 'Theory'),
('DEL-502',   'Microwave and Radar', 5, 5, 'Theory'),
('DEL-503',   'Television Engineering', 5, 5, 'Theory'),
('DEL-504',   'Computer System Architecture', 5, 5, 'Theory'),
('DME-506',   'Industrial Management', 5, 5, 'Theory'),
('DEL-511',   'Electronic Devices & Circuits-III Lab', 5, 5, 'Practical'),
('DEL-512',   'Microwave and Radar Lab', 5, 5, 'Practical'),
('DEL-513',   'Television Engineering Lab', 5, 5, 'Practical'),
('DEL-517',   'Electronics Workshop', 5, 5, 'Practical'),
('DEL-601',   'Advance Communication Systems', 5, 6, 'Theory'),
('DEL-602',   'Electronics Circuit Design', 5, 6, 'Theory'),
('DEL-603',   'Microcontrollers & Embedded Systems', 5, 6, 'Theory'),
('DEL-604',   'Consumer Electronics', 5, 6, 'Theory'),
('DEL-605',   'VLSI Design', 5, 6, 'Theory'),
('DEL-611',   'Advance Communication Systems Lab', 5, 6, 'Practical'),
('DEL-613',   'Microcontrollers & Embedded Systems Lab', 5, 6, 'Practical'),
('DEL-620',   'Project', 5, 6, 'Practical'),
('DEL-630',   'Industrial Training & Visits', 5, 6, 'Practical');
