INSERT IGNORE INTO courses (code, name, department_id, semester, subject_type) VALUES
('DMES-101',  'Communication Skills-I', 2, 1, 'Theory'),
('DMEP-102',  'Applied Physics', 2, 1, 'Theory'),
('DMEM-104',  'Applied Maths-I', 2, 1, 'Theory'),
('DCE-M105',  'Applied Mechanics', 2, 1, 'Theory'),
('DME-106',   'Workshop Technology', 2, 1, 'Theory'),
('DMEP-112',  'Applied Physics Lab', 2, 1, 'Practical'),
('DME-115',   'Applied Mechanics Lab', 2, 1, 'Practical'),
('DME-M116',  'Workshop Practice-I', 2, 1, 'Practical'),
('DME-117',   'Engineering Drawing-I', 2, 1, 'Practical'),
('DMEM-201',  'Applied Maths-II', 2, 2, 'Theory'),
('DMEC-202',  'Applied Chemistry', 2, 2, 'Theory'),
('DEE-203',   'Elements of Electrical Engineering', 2, 2, 'Theory'),
('DME-204',   'Engineering Drawing-II', 2, 2, 'Theory'),
('DME-205',   'Applied Thermodynamics', 2, 2, 'Theory'),
('DMEC-212',  'Applied Chemistry Lab', 2, 2, 'Practical'),
('DEE-213',   'Elements of Electrical Engineering Lab', 2, 2, 'Practical'),
('DME-214',   'Workshop Practice-II', 2, 2, 'Practical'),
('DME-215',   'Applied Thermodynamics Lab', 2, 2, 'Practical'),
('DEE-301',   'Electrical Technology', 2, 3, 'Theory'),
('DME-302',   'Fluid Mechanics & Fluid Machines', 2, 3, 'Theory'),
('DME-303',   'Thermal Engineering', 2, 3, 'Theory'),
('DME-304',   'Machine Drawing', 2, 3, 'Theory'),
('DCA-M305',  'Computer Applications', 2, 3, 'Theory'),
('DEE-311',   'Electrical Technology Lab', 2, 3, 'Practical'),
('DME-312',   'Fluid Mechanics & Fluid Machines Lab', 2, 3, 'Practical'),
('DME-313',   'Thermal Engineering Lab', 2, 3, 'Practical'),
('DCA-M315',  'Computer Applications Lab', 2, 3, 'Practical'),
('DMES-401',  'Communication Skills-II', 2, 4, 'Theory'),
('DME-402',   'Manufacturing Process-I', 2, 4, 'Theory'),
('DME-403',   'Mechanics of Solid', 2, 4, 'Theory'),
('DME-404',   'Material Science', 2, 4, 'Theory'),
('DME-405',   'Theory of Machine', 2, 4, 'Theory'),
('DME-412',   'Manufacturing Process-I Lab', 2, 4, 'Practical'),
('DME-413',   'Mechanics of Solid Lab', 2, 4, 'Practical'),
('DME-414',   'Material Science Lab', 2, 4, 'Practical'),
('DME-415',   'Theory of Machine Lab', 2, 4, 'Practical'),
('DME-501',   'Computer Aided Design & Manufacturing', 2, 5, 'Theory'),
('DME-502',   'Manufacturing Process-II', 2, 5, 'Theory'),
('DME-503',   'Estimating & Costing', 2, 5, 'Theory'),
('DME-504',   'Automobile Engineering', 2, 5, 'Theory'),
('DME-505',   'Renewable Energy Sources', 2, 5, 'Theory'),
('DME-512',   'Manufacturing Process-II Lab', 2, 5, 'Practical'),
('DME-513',   'Auto CAD Lab', 2, 5, 'Practical'),
('DME-514',   'Automobile Engineering Lab', 2, 5, 'Practical'),
('DME-515',   'Renewable Energy Sources Lab', 2, 5, 'Practical'),
('DME-601',   'Industrial Management', 2, 6, 'Theory'),
('DME-602',   'Machine Design', 2, 6, 'Theory'),
('DME-603',   'Power Plant Engineering', 2, 6, 'Theory'),
('DME-604',   'Metrology and Measurement', 2, 6, 'Theory'),
('DME-605',   'Refrigeration & Air-Conditioning', 2, 6, 'Theory'),
('DME-614',   'Metrology and Measurement Lab', 2, 6, 'Practical'),
('DME-615',   'Refrigeration & Air-Conditioning Lab', 2, 6, 'Practical'),
('DME-620',   'Project', 2, 6, 'Practical'),
('DME-630',   'Industrial Training & Visits', 2, 6, 'Practical');
