INSERT IGNORE INTO courses (code, name, department_id, semester, subject_type) VALUES
('DEES-101',  'Communication Skills-I', 3, 1, 'Theory'),
('DEEC-103',  'Applied Chemistry', 3, 1, 'Theory'),
('DEEM-104',  'Applied Mathematics-I', 3, 1, 'Theory'),
('DCE-EE105', 'Applied Mechanics', 3, 1, 'Theory'),
('DEE-106',   'Fundamentals of Electrical Engineering', 3, 1, 'Theory'),
('DEEC-113',  'Applied Chemistry Lab', 3, 1, 'Practical'),
('DCE-EE115', 'Applied Mechanics Lab', 3, 1, 'Practical'),
('DEE-116',   'Fundamentals of Electrical Engineering Lab', 3, 1, 'Practical'),
('DME-EE117', 'Engineering Drawing-I', 3, 1, 'Practical'),
('DEEM-201',  'Applied Mathematics-II', 3, 2, 'Theory'),
('DEEP-202',  'Applied Physics', 3, 2, 'Theory'),
('DME-EE203', 'Elements of Mechanical Engineering', 3, 2, 'Theory'),
('DEE-204',   'Electrical Engineering Materials', 3, 2, 'Theory'),
('DEL-206',   'Basic Electronics', 3, 2, 'Theory'),
('DEEP-212',  'Applied Physics Lab', 3, 2, 'Practical'),
('DME-EE213', 'Elements of Mechanical Engineering Lab', 3, 2, 'Practical'),
('DEL-216',   'Basic Electronics Lab', 3, 2, 'Practical'),
('DME-217',   'Workshop Practice', 3, 2, 'Practical'),
('DEE-302',   'Measurements & Measuring Instruments', 3, 3, 'Theory'),
('DEL-EE305', 'Digital Electronics & Microprocessor', 3, 3, 'Theory'),
('DCA-EE305', 'Computer Applications', 3, 3, 'Theory'),
('DEE-306',   'Electrical Design Drawing & Estimating', 3, 3, 'Theory'),
('DME-306',   'Thermo Fluids', 3, 3, 'Theory'),
('DEE-312',   'Measurements & Measuring Instruments Lab', 3, 3, 'Practical'),
('DEL-EE313', 'Digital Electronics & Microprocessor Lab', 3, 3, 'Practical'),
('DCA-EE315', 'Computer Applications Lab', 3, 3, 'Practical'),
('DME-316',   'Thermo Fluids Lab', 3, 3, 'Practical'),
('DEES-401',  'Communication Skills-II', 3, 4, 'Theory'),
('DEE-402',   'Generation of Electrical Energy', 3, 4, 'Theory'),
('DEE-403',   'Network Analysis', 3, 4, 'Theory'),
('DEE-404',   'Electrical Machines-I', 3, 4, 'Theory'),
('DEE-405',   'Power Electronics', 3, 4, 'Theory'),
('DEE-413',   'Network Analysis Lab', 3, 4, 'Practical'),
('DEE-414',   'Electrical Machines-I Lab', 3, 4, 'Practical'),
('DEE-415',   'Power Electronics Lab', 3, 4, 'Practical'),
('DEE-416',   'Electrical Workshop', 3, 4, 'Practical'),
('DEE-501',   'Electrical Machines-II', 3, 5, 'Theory'),
('DEE-502',   'Electrical Troubleshooting', 3, 5, 'Theory'),
('DEE-503',   'Control System Engineering', 3, 5, 'Theory'),
('DEE-504',   'Electrical Instrumentation', 3, 5, 'Theory'),
('DME-EE506', 'Industrial Management', 3, 5, 'Theory'),
('DEE-511',   'Electrical Machines-II Lab', 3, 5, 'Practical'),
('DEE-512',   'Electrical Troubleshooting Lab', 3, 5, 'Practical'),
('DEE-513',   'Control System Engineering Lab', 3, 5, 'Practical'),
('DEE-514',   'Electrical Instrumentation Lab', 3, 5, 'Practical'),
('DEE-601',   'Transmission & Distribution', 3, 6, 'Theory'),
('DEE-602',   'Switch Gear & Protection', 3, 6, 'Theory'),
('DEE-603',   'Special Purpose Machines', 3, 6, 'Theory'),
('DEE-604',   'Utilization & Traction', 3, 6, 'Theory'),
('DEE-605',   'Electrical Energy Management', 3, 6, 'Theory'),
('DEE-612',   'Switch Gear & Protection Lab', 3, 6, 'Practical'),
('DEE-613',   'Special Purpose Machines Lab', 3, 6, 'Practical'),
('DEE-620',   'Project', 3, 6, 'Practical'),
('DEE-630',   'Industrial Training & Visits', 3, 6, 'Practical');
